require('./database');
const Product = require('../models/product');

Promise.all([Product.deleteMany({})])

.then(function() {
	return Product.create([
		{name: 'Garden Canary', category: 'food', brand: 'Sleek & Sassy', price: 1.99, unitPrice: 'pound'},
		{name: 'Garden Budgie', category: 'food', brand: 'Sleek & Sassy', price: 1.99, unitPrice: 'pound'},
		{name: 'Garden Finch', category: 'food', brand: 'Sleek & Sassy', price: 1.99, unitPrice: 'pound'},
		{name: 'Small Hookbill with Sunflower', category: 'food', brand: 'Sleek & Sassy', price: 1.99, unitPrice: 'pound'},
		{name: 'Small Hookbill no Sunflower', category: 'food', brand: 'Sleek & Sassy', price: 1.99, unitPrice: 'pound'},
		{name: 'Large Hookbill with Sunflower', category: 'food', brand: 'Sleek & Sassy', price: 2.49, unitPrice: 'pound'},
		{name: 'Large Hookbill no Sunflower', category: 'food', brand: 'Sleek & Sassy', price: 2.49, unitPrice: 'pound'},
		{name: 'Nutty Garden & Grain with Sunflower', category: 'food', brand: 'Sleek & Sassy', price: 2.99, unitPrice: 'pound'},
		{name: 'Hot & Hardy', description: 'Cook 30-40 minutes', category: 'food', brand: 'Sleek & Sassy', price: 2.99, unitPrice: 'pound'},
		{name: 'Parakeet Deluxe', category: 'food', brand: 'BiZee Bird Seed Mix', price: 1.99, unitPrice: 'pound'},
		{name: 'Cockatiel Delight', category: 'food', brand: 'BiZee Bird Seed Mix', price: 2.25, unitPrice: 'pound'},
		{name: 'Small Hookbill with Sunflower', category: 'food', brand: 'BiZee Bird Seed Mix', price: 1.99, unitPrice: 'pound'},
		{name: 'Small Hookbill no Sunflower', category: 'food', brand: 'BiZee Bird Seed Mix', price: 1.99, unitPrice: 'pound'},
		{name: 'Large Hookbill with Sunflower', category: 'food', brand: 'BiZee Bird Seed Mix', price: 2.49, unitPrice: 'pound'},
		{name: 'Large Hookbill no Sunflower', category: 'food', brand: 'BiZee Bird Seed Mix', price: 2.49, unitPrice: 'pound'},
		{name: 'Jungle Romance no Nuts', category: 'food', brand: 'BiZee Bird Seed Mix', price: 4.99, unitPrice: 'pound'},
		{name: 'Paradise Trail with Nuts', category: 'food', brand: 'BiZee Bird Seed Mix', price: 5.99, unitPrice: 'pound'},
		{name: 'Garden Delight no Nuts', category: 'food', brand: 'BiZee Bird Seed Mix', price: 7.49, unitPrice: 'pound'},
		{name: 'Shelled Party Mix with Nuts', category: 'food', brand: 'BiZee Bird Seed Mix', price: 7.99, unitPrice: 'pound'},
		{name: 'Buckwheat', category: 'food', brand: 'Individual Seeds', price: 1.49, unitPrice: 'pound'},
		{name: 'Safflower', category: 'food', brand: 'Individual Seeds', price: 1.49, unitPrice: 'pound'},
		{name: 'Oat Groats Shelled Oats', category: 'food', brand: 'Individual Seeds', price: 1.49, unitPrice: 'pound'},
		{name: 'Hemp Seed', category: 'food', brand: 'Individual Seeds', price: 4.50, unitPrice: 'pound'},
		{name: 'Spay Millet', category: 'food', brand: 'Individual Seeds', price: 0.60, unitPrice: 'item'},
		{name: 'Pumpkin Seeds', category: 'food', brand: 'Individual Seeds', price: 6.99, unitPrice: 'pound'},
		{name: 'Parakeet', category: 'food', brand: 'Volkman Seeds', price: 4.99, unitPrice: '2 pound bag'},
		{name: 'Parakeet', category: 'food', brand: 'Volkman Seeds', price: 8.99, unitPrice: '4 pound bag'},
		{name: 'Cockatiel with Sunflower', category: 'food', brand: 'Volkman Seeds', price: 4.99, unitPrice: '2 pound bag'},
		{name: 'Cockatiel with Sunflower', category: 'food', brand: 'Volkman Seeds', price: 8.99, unitPrice: '4 pound bag'},
		{name: 'Cockatiel no Sunflower', category: 'food', brand: 'Volkman Seeds', price: 4.99, unitPrice: '2 pound bag'},
		{name: 'Cockatiel no Sunflower', category: 'food', brand: 'Volkman Seeds', price: 8.99, unitPrice: '4 pound bag'},
		{name: 'Lovebird Mix', category: 'food', brand: 'Volkman Seeds', price: 5.99, unitPrice: '2 pound bag'},
		{name: 'Lovebird Mix', category: 'food', brand: 'Volkman Seeds', price: 9.99, unitPrice: '4 pound bag'},
		{name: 'Hookbill', category: 'food', brand: 'Volkman Seeds', price: 5.99, unitPrice: '2 pound bag'},
		{name: 'Hookbill', category: 'food', brand: 'Volkman Seeds', price: 9.99, unitPrice: '4 pound bag'},
		{name: 'Eclectus Mix', category: 'food', brand: 'Volkman Seeds', price: 17.99, unitPrice: '4 pound bag'},
		{name: 'Super Parrot Mix', category: 'food', brand: 'Volkman Seeds', price: 11.99, unitPrice: '4 pound bag'},
		{name: 'Parakeet', category: 'food', brand: 'Dr. Harvey\'s Organic Mix', price: 19.99, unitPrice: '2 pound bag'},
		{name: 'Cockatiel', category: 'food', brand: 'Dr. Harvey\'s Organic Mix', price: 19.99, unitPrice: '2 pound bag'},
		{name: 'Perfect Parrot', category: 'food', brand: 'Dr. Harvey\'s Organic Mix', price: 39.99, unitPrice: '4 pound bag'},
		{name: 'Perfect Parrot', category: 'food', brand: 'Dr. Harvey\'s Organic Mix', price: 9.99, unitPrice: '1 pound bag'},
		{name: 'Pine Nuts', category: 'food', brand: 'Assorted Nuts', price: 14.99, unitPrice: 'pound'},
		{name: 'Almonds', category: 'food', brand: 'Assorted Nuts', price: 5.99, unitPrice: 'pound'},
		{name: 'Walnuts', category: 'food', brand: 'Assorted Nuts', price: 7.99, unitPrice: 'pound'},
		{name: 'Peanuts', category: 'food', brand: 'Assorted Nuts', price: 2.99, unitPrice: 'pound'},
		{name: 'Tropical Cockatiel', category: 'food', brand: 'Lafeber\'s', price: 9.99, unitPrice: 'item'},
		{name: 'Tropical Parrot', category: 'food', brand: 'Lafeber\'s', price: 9.99, unitPrice: 'item'},
		{name: 'Tropical Macaw', category: 'food', brand: 'Lafeber\'s', price: 9.99, unitPrice: 'item'},
		{name: 'Sunny Orchard', category: 'food', brand: 'Lafeber\'s', price: 9.99, unitPrice: 'item'},
		{name: 'Garden Veggie', category: 'food', brand: 'Lafeber\'s', price: 9.99, unitPrice: 'item'},
		{name: 'El Paso', category: 'food', brand: 'Lafeber\'s', price: 9.99, unitPrice: 'item'},
		{name: 'Avi Cakes Cockatiel', category: 'food', brand: 'Lafeber\'s', price: 6.99, unitPrice: '8 ounces'},
		{name: 'Avi Cakes Parrot', category: 'food', brand: 'Lafeber\'s', price: 8.99, unitPrice: '12 ounces'},
		{name: 'Avi Cakes Macaw', category: 'food', brand: 'Lafeber\'s', price: 10.99, unitPrice: '1 pound'},
		{name: 'Nutriberries Cockatiel', category: 'food', brand: 'Lafeber\'s', price: 9.99, unitPrice: 'item'},
		{name: 'Nutriberries Parrot', category: 'food', brand: 'Lafeber\'s', price: 9.99, unitPrice: 'item'},
		{name: 'TOP All Size Hookbills', category: 'food', brand: 'Totally Organic Pellets', price: 5.99, unitPrice: '1 pound bag'},
		{name: 'TOP All Size Hookbills', category: 'food', brand: 'Totally Organic Pellets', price: 17.99, unitPrice: '4 pound bag'},
		{name: 'TOP Crumpet Pellets For Little Birds', category: 'food', brand: 'Totally Organic Pellets', price: 5.99, unitPrice: '1 pound bag'},
		{name: 'TOP Soak & Dry Seeds Mix', category: 'food', brand: 'Totally Organic Pellets', price: 6.99, unitPrice: '1 pound bag'},
		{name: 'TOP Soak & Dry Seeds Mix', category: 'food', brand: 'Totally Organic Pellets', price: 17.99, unitPrice: '5 pound bag'},
		{name: 'TOP Napoleon Seed Mix', category: 'food', brand: 'Totally Organic Pellets', price: 6.99, unitPrice: '1 pound bag'},
		{name: 'TOP Napoleon Seed Mix', category: 'food', brand: 'Totally Organic Pellets', price: 17.99, unitPrice: '5 pound bag'},
		{name: 'Adult Lifetime Fine', category: 'food', brand: 'Harrison\'s', price: 9.99, unitPrice: '1 pound bag'},
		{name: 'Adult Lifetime Fine', category: 'food', brand: 'Harrison\'s', price: 34.99, unitPrice: '5 pound bag'},
		{name: 'Adult Lifetime Coarse', category: 'food', brand: 'Harrison\'s', price: 9.99, unitPrice: '1 pound bag'},
		{name: 'Adult Lifetime Coarse', category: 'food', brand: 'Harrison\'s', price: 34.99, unitPrice: '5 pound bag'},
		{name: 'Adult Pepper Lifetime Coarse', category: 'food', brand: 'Harrison\'s', price: 9.99, unitPrice: '1 pound bag'},
		{name: 'Adult Pepper Lifetime Coarse', category: 'food', brand: 'Harrison\'s', price: 34.99, unitPrice: '5 pound bag'},
		{name: 'High Potency Fine', category: 'food', brand: 'Harrison\'s', price: 10.99, unitPrice: '1 pound bag'},
		{name: 'High Potency Fine', category: 'food', brand: 'Harrison\'s', price: 36.99, unitPrice: '5 pound bag'},
		{name: 'High Potency Coarse', category: 'food', brand: 'Harrison\'s', price: 10.99, unitPrice: '1 pound bag'},
		{name: 'High Potency Coarse', category: 'food', brand: 'Harrison\'s', price: 36.99, unitPrice: '5 pound bag'},
		{name: 'ZuPreem Fruit Cocktail', category: 'food', brand: 'ZuPreem Pellets', price: 4.99, unitPrice: 'pound'},
		{name: 'ZuPreem Fruit Medium Parrot', category: 'food', brand: 'ZuPreem Pellets', price: 4.99, unitPrice: 'pound'},
		{name: 'ZuPreem Fruit Large Parrot', category: 'food', brand: 'ZuPreem Pellets', price: 4.99, unitPrice: 'pound'},
		{name: 'Canary Fruit', category: 'food', brand: 'ZuPreem Pellets', price: 15.99, unitPrice: 'item'},
		{name: 'Parakeet Fruit', category: 'food', brand: 'ZuPreem Pellets', price: 15.99, unitPrice: 'item'},
		{name: 'Cockatiel Natural', category: 'food', brand: 'ZuPreem Pellets', price: 15.99, unitPrice: 'item'},
		{name: 'Parrot Natural', category: 'food', brand: 'ZuPreem Pellets', price: 15.99, unitPrice: 'item'},
		{name: 'Roudybush Mini', category: 'food', brand: 'Roudybush', price: 17.99, unitPrice: '44 ounces'},
		{name: 'Roudybush Small', category: 'food', brand: 'Roudybush', price: 17.99, unitPrice: '44 ounces'},
		{name: 'Roudybush Medium', category: 'food', brand: 'Roudybush', price: 17.99, unitPrice: '44 ounces'},
		{name: 'Roudybush Large', category: 'food', brand: 'Roudybush', price: 17.99, unitPrice: '44 ounces'},
	])
})
.then(function() {
	require('mongoose').connection.close();
	process.exit();
})